// Localized strings for plan generation (meal databases, timing, coach advice)

const enMeals = {
  omnivore: {
    breakfast: [
      {
        name: 'Scrambled Eggs with Avocado Toast',
        description: '3 large eggs, 2 slices whole wheat toast, 1/2 avocado, 1 orange',
        prepTime: '10 minutes',
        difficulty: 'Easy',
        alternatives: ['Oatmeal with berries and nuts', 'Greek yogurt with granola'],
      },
      {
        name: 'Oatmeal with Berries & Almonds',
        description: '1 cup oats, 1 banana, 1/2 cup blueberries, 1/4 cup almonds, honey',
        prepTime: '15 minutes',
        difficulty: 'Easy',
        alternatives: ['Pancakes with lean bacon', 'Smoothie with protein powder'],
      },
      {
        name: 'Greek Yogurt Parfait',
        description: '1.5 cups Greek yogurt, 1/2 cup granola, 1/2 cup mixed berries, honey drizzle',
        prepTime: '5 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Cottage cheese with fruit', 'Protein smoothie'],
      },
      {
        name: 'Chicken Sausage Breakfast',
        description: '2 chicken sausages, 2 slices whole wheat toast, 1 tbsp almond butter, berries',
        prepTime: '10 minutes',
        difficulty: 'Easy',
        alternatives: ['Bacon and eggs', 'Turkey sausage'],
      },
    ],
    lunch: [
      {
        name: 'Grilled Chicken Breast with Rice & Broccoli',
        description: '150g grilled chicken breast, 150g brown rice, 150g steamed broccoli, olive oil',
        prepTime: '20 minutes',
        difficulty: 'Medium',
        alternatives: ['Turkey with sweet potato', 'Salmon with rice'],
      },
      {
        name: 'Turkey & Veggie Wrap',
        description: 'Whole wheat wrap, 100g sliced turkey, lettuce, tomato, hummus, avocado',
        prepTime: '5 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Chicken wrap', 'Tuna wrap'],
      },
      {
        name: 'Salmon with Sweet Potato & Asparagus',
        description: '150g baked salmon, 150g sweet potato, 150g steamed asparagus, lemon',
        prepTime: '25 minutes',
        difficulty: 'Medium',
        alternatives: ['Cod with potatoes', 'Halibut with vegetables'],
      },
      {
        name: 'Lean Beef with Pasta & Tomato Sauce',
        description: '120g lean ground beef, 1.5 cups whole wheat pasta, tomato sauce, vegetables',
        prepTime: '20 minutes',
        difficulty: 'Medium',
        alternatives: ['Turkey meatballs', 'Chicken pasta'],
      },
    ],
    dinner: [
      {
        name: 'Grilled Steak with Roasted Vegetables',
        description: '150g grilled steak (lean cut), roasted broccoli and carrots, sweet potato',
        prepTime: '30 minutes',
        difficulty: 'Medium',
        alternatives: ['Grilled chicken', 'Baked fish'],
      },
      {
        name: 'Baked Chicken with Quinoa & Green Beans',
        description: '150g baked chicken breast, 150g quinoa, 150g steamed green beans, olive oil',
        prepTime: '30 minutes',
        difficulty: 'Easy',
        alternatives: ['Turkey breast', 'Baked fish'],
      },
      {
        name: 'Fish Tacos with Cabbage Slaw',
        description: '150g baked white fish, 2 whole grain tortillas, cabbage slaw, lime, cilantro',
        prepTime: '20 minutes',
        difficulty: 'Medium',
        alternatives: ['Chicken tacos', 'Shrimp tacos'],
      },
      {
        name: 'Pork Tenderloin with Roasted Root Vegetables',
        description: '150g baked pork tenderloin, roasted sweet potato and brussels sprouts',
        prepTime: '35 minutes',
        difficulty: 'Medium',
        alternatives: ['Beef tenderloin', 'Chicken breast'],
      },
    ],
    snack: [
      {
        name: 'Protein Shake',
        description: 'Protein powder, banana, 1 tbsp peanut butter, almond milk, ice',
        prepTime: '5 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Greek yogurt', 'Protein bar'],
      },
      {
        name: 'Almonds & Dried Fruit Mix',
        description: '1/4 cup almonds, 2 tbsp dried cranberries, 2 tbsp raisins',
        prepTime: '0 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Mixed nuts', 'Trail mix'],
      },
      {
        name: 'Cottage Cheese with Berries',
        description: '150g low-fat cottage cheese, 1/2 cup mixed berries, 1 tbsp honey',
        prepTime: '2 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Greek yogurt', 'Protein pudding'],
      },
      {
        name: 'Apple with Almond Butter',
        description: '1 medium apple, 2 tbsp almond butter',
        prepTime: '2 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Banana with peanut butter', 'Rice cakes with butter'],
      },
    ],
  },
  vegetarian: {
    breakfast: [
      {
        name: 'Scrambled Eggs with Avocado Toast',
        description: '3 large eggs, 2 slices whole wheat toast, 1/2 avocado, 1 orange',
        prepTime: '10 minutes',
        difficulty: 'Easy',
        alternatives: ['Oatmeal with protein powder', 'Greek yogurt with granola'],
      },
      {
        name: 'Tofu Scramble with Mushrooms',
        description: '150g firm tofu, mushrooms, spinach, onions, 2 slices toast, olive oil',
        prepTime: '15 minutes',
        difficulty: 'Medium',
        alternatives: ['Vegetable frittata', 'Chickpea scramble'],
      },
      {
        name: 'Greek Yogurt Parfait',
        description: '1.5 cups Greek yogurt, 1/2 cup granola, 1/2 cup berries, honey',
        prepTime: '5 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Cottage cheese parfait', 'Plant-based yogurt'],
      },
      {
        name: 'Cottage Cheese Pancakes',
        description: '1 cup cottage cheese blended with eggs, whole grain flour, berries on top',
        prepTime: '15 minutes',
        difficulty: 'Medium',
        alternatives: ['Oatmeal pancakes', 'Protein pancakes'],
      },
    ],
    lunch: [
      {
        name: 'Chickpea & Quinoa Salad',
        description: '1 cup cooked chickpeas, 1 cup quinoa, vegetables, tahini dressing, lemon',
        prepTime: '15 minutes',
        difficulty: 'Easy',
        alternatives: ['Lentil salad', 'Bean & grain bowl'],
      },
      {
        name: 'Vegetable Burger with Sweet Potato Fries',
        description: 'Veggie burger (store-bought), whole grain bun, sweet potato fries, veggies',
        prepTime: '20 minutes',
        difficulty: 'Easy',
        alternatives: ['Black bean burger', 'Falafel wrap'],
      },
      {
        name: 'Lentil Soup with Whole Grain Bread',
        description: '1 serving lentil soup, 1 slice whole grain bread with hummus, side salad',
        prepTime: '10 minutes (if prepared)',
        difficulty: 'Easy',
        alternatives: ['Bean soup', 'Vegetable soup'],
      },
      {
        name: 'Greek Salad with Chickpeas & Feta',
        description: 'Mixed greens, chickpeas, feta cheese, olives, cucumber, tomato, olive oil',
        prepTime: '10 minutes',
        difficulty: 'Easy',
        alternatives: ['Caprese salad', 'Mediterranean salad'],
      },
    ],
    dinner: [
      {
        name: 'Baked Tofu with Roasted Vegetables & Rice',
        description: '200g marinated baked tofu, roasted broccoli and carrots, 1 cup brown rice',
        prepTime: '30 minutes',
        difficulty: 'Medium',
        alternatives: ['Tempeh stir-fry', 'Seitan with vegetables'],
      },
      {
        name: 'Lentil & Vegetable Curry with Rice',
        description: '1.5 cups cooked lentils, curry sauce, vegetables, 1 cup brown rice',
        prepTime: '30 minutes',
        difficulty: 'Medium',
        alternatives: ['Chickpea curry', 'Bean curry'],
      },
      {
        name: 'Vegetable Stir-Fry with Cashews & Quinoa',
        description: 'Mixed vegetables, 1/4 cup cashews, 1 cup quinoa, soy-ginger sauce',
        prepTime: '20 minutes',
        difficulty: 'Easy',
        alternatives: ['Tofu stir-fry', 'Tempeh stir-fry'],
      },
      {
        name: 'Chickpea Pasta with Marinara & Greens',
        description: '1.5 cups whole wheat pasta, chickpea-based pasta, marinara, spinach',
        prepTime: '20 minutes',
        difficulty: 'Easy',
        alternatives: ['Lentil pasta', 'Bean pasta'],
      },
    ],
    snack: [
      {
        name: 'Protein Shake',
        description: 'Plant-based protein powder, banana, almond butter, almond milk',
        prepTime: '5 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Plant-based yogurt', 'Protein bar'],
      },
      {
        name: 'Mixed Nuts & Seeds',
        description: '1/4 cup almonds, cashews, pumpkin seeds, sunflower seeds',
        prepTime: '0 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Trail mix', 'Nut butter on crackers'],
      },
      {
        name: 'Hummus with Vegetable Sticks',
        description: '1/4 cup hummus, carrots, celery, bell peppers',
        prepTime: '5 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Guacamole with veggies', 'Tahini dip'],
      },
      {
        name: 'Greek Yogurt with Granola',
        description: '150g Greek yogurt, 1/4 cup granola, berries',
        prepTime: '2 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Cottage cheese', 'Plant-based yogurt'],
      },
    ],
  },
  vegan: {
    breakfast: [
      {
        name: 'Oatmeal with Plant Protein & Berries',
        description: '1 cup oats, plant-based protein powder, mixed berries, almond milk, honey',
        prepTime: '15 minutes',
        difficulty: 'Easy',
        alternatives: ['Smoothie bowl', 'Tofu scramble'],
      },
      {
        name: 'Tofu Scramble with Mushrooms & Toast',
        description: '150g firm tofu, mushrooms, spinach, 2 slices whole grain toast, olive oil',
        prepTime: '15 minutes',
        difficulty: 'Medium',
        alternatives: ['Chickpea scramble', 'Tempeh scramble'],
      },
      {
        name: 'Smoothie Bowl',
        description: 'Blended banana, berries, plant milk, topped with granola, coconut, seeds',
        prepTime: '10 minutes',
        difficulty: 'Easy',
        alternatives: ['Acai bowl', 'Green smoothie bowl'],
      },
      {
        name: 'Chia Seed Pudding with Fruit',
        description: 'Chia seeds, almond milk, maple syrup, fresh fruit, granola topping',
        prepTime: '5 minutes (+ overnight)',
        difficulty: 'Very Easy',
        alternatives: ['Hemp seed pudding', 'Flax seed pudding'],
      },
    ],
    lunch: [
      {
        name: 'Chickpea & Vegetable Curry with Rice',
        description: '1 cup cooked chickpeas, curry sauce, vegetables, 1 cup brown rice',
        prepTime: '25 minutes',
        difficulty: 'Medium',
        alternatives: ['Lentil curry', 'Tofu curry'],
      },
      {
        name: 'Lentil & Walnut Tacos',
        description: 'Seasoned cooked lentils, walnuts, whole grain tortillas, salsa, lettuce',
        prepTime: '15 minutes',
        difficulty: 'Easy',
        alternatives: ['Black bean tacos', 'Tofu tacos'],
      },
      {
        name: 'Tempeh & Vegetable Stir-Fry with Quinoa',
        description: '150g marinated tempeh, mixed vegetables, quinoa, soy-ginger sauce',
        prepTime: '20 minutes',
        difficulty: 'Medium',
        alternatives: ['Tofu stir-fry', 'Seitan stir-fry'],
      },
      {
        name: 'Hummus Wrap with Roasted Vegetables',
        description: 'Whole grain wrap, hummus, roasted vegetables, tahini sauce',
        prepTime: '15 minutes',
        difficulty: 'Easy',
        alternatives: ['Falafel wrap', 'Tofu wrap'],
      },
    ],
    dinner: [
      {
        name: 'Baked Tofu with Roasted Vegetables & Farro',
        description: '200g marinated baked tofu, roasted broccoli, farro, lemon-herb dressing',
        prepTime: '30 minutes',
        difficulty: 'Medium',
        alternatives: ['Tempeh', 'Seitan'],
      },
      {
        name: 'Lentil Bolognese with Whole Wheat Pasta',
        description: '1.5 cups cooked lentils, marinara, 1.5 cups pasta, steamed spinach',
        prepTime: '25 minutes',
        difficulty: 'Medium',
        alternatives: ['Mushroom bolognese', 'Chickpea bolognese'],
      },
      {
        name: 'Vegetable & Black Bean Enchiladas',
        description: 'Whole grain tortillas, black beans, vegetables, salsa, cashew cream sauce',
        prepTime: '30 minutes',
        difficulty: 'Medium',
        alternatives: ['Chickpea enchiladas', 'Bean enchiladas'],
      },
      {
        name: 'Chickpea & Spinach Curry with Coconut Rice',
        description: '1 cup chickpeas, spinach, coconut curry, coconut rice',
        prepTime: '25 minutes',
        difficulty: 'Medium',
        alternatives: ['Tofu curry', 'Lentil curry'],
      },
    ],
    snack: [
      {
        name: 'Vegan Protein Shake',
        description: 'Plant-based protein powder, banana, almond butter, almond milk, ice',
        prepTime: '5 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Smoothie with nuts', 'Plant yogurt'],
      },
      {
        name: 'Mixed Nuts & Seeds',
        description: '1/4 cup almonds, cashews, pumpkin seeds, sunflower seeds',
        prepTime: '0 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Trail mix', 'Nut butter with fruit'],
      },
      {
        name: 'Coconut Yogurt with Berries',
        description: '150g coconut yogurt, 1/2 cup mixed berries, 1 tbsp honey/maple syrup',
        prepTime: '2 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Almond yogurt', 'Oat yogurt'],
      },
      {
        name: 'Fruit with Almond Butter',
        description: 'Apple or banana with 2 tbsp almond butter',
        prepTime: '2 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Tahini on fruit', 'Cashew butter on fruit'],
      },
    ],
  },
  keto: {
    breakfast: [
      {
        name: 'Scrambled Eggs with Bacon & Avocado',
        description: '4 large eggs, 3 slices bacon, 1/2 avocado, butter',
        prepTime: '10 minutes',
        difficulty: 'Easy',
        alternatives: ['Egg muffins', 'Omelet with cheese'],
      },
      {
        name: 'Greek Yogurt with Nuts & Seeds',
        description: '150g full-fat Greek yogurt, 1/4 cup nuts, 2 tbsp seeds, MCT oil',
        prepTime: '2 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Cottage cheese', 'Heavy cream with berries'],
      },
      {
        name: 'Smoked Salmon with Cream Cheese',
        description: '100g smoked salmon, 50g cream cheese, cucumber slices, capers',
        prepTime: '5 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Mackerel with avocado', 'Sardines with cream cheese'],
      },
      {
        name: 'Butter Coffee with MCT Oil',
        description: 'Black coffee, 1 tbsp butter, 1 tbsp MCT oil, pinch of salt',
        prepTime: '5 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Bulletproof coffee', 'Heavy cream coffee'],
      },
    ],
    lunch: [
      {
        name: 'Grilled Ribeye with Butter & Vegetables',
        description: '150g grilled ribeye, garlic butter, steamed broccoli and zucchini',
        prepTime: '25 minutes',
        difficulty: 'Medium',
        alternatives: ['Salmon', 'Lamb chops'],
      },
      {
        name: 'Tuna Salad Lettuce Wraps',
        description: '150g canned tuna (in oil), mayo, celery, butter lettuce wraps',
        prepTime: '5 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Chicken salad', 'Egg salad'],
      },
      {
        name: 'Bacon & Cheese Burger (no bun)',
        description: '150g ground beef burger, 2 slices cheese, bacon, mayo, pickles',
        prepTime: '10 minutes',
        difficulty: 'Easy',
        alternatives: ['Turkey burger', 'Lamb burger'],
      },
      {
        name: 'Caprese Salad with Olive Oil',
        description: 'Fresh mozzarella, tomato, basil, olive oil, balsamic (minimal)',
        prepTime: '5 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Spinach salad with bacon', 'Kale salad with olive oil'],
      },
    ],
    dinner: [
      {
        name: 'Grilled Salmon with Hollandaise',
        description: '150g grilled salmon, hollandaise sauce, roasted asparagus',
        prepTime: '25 minutes',
        difficulty: 'Medium',
        alternatives: ['Halibut with butter', 'Cod with hollandaise'],
      },
      {
        name: 'Ribeye Steak with Compound Butter',
        description: '200g grilled ribeye, herb compound butter, roasted Brussels sprouts',
        prepTime: '25 minutes',
        difficulty: 'Medium',
        alternatives: ['NY Strip', 'Filet mignon'],
      },
      {
        name: 'Shrimp Scampi with Zucchini Noodles',
        description: '200g shrimp, garlic butter, zucchini noodles, lemon, parsley',
        prepTime: '15 minutes',
        difficulty: 'Easy',
        alternatives: ['Scallops', 'Lobster'],
      },
      {
        name: 'Pork Chops with Creamy Mushroom Sauce',
        description: '2 pork chops, heavy cream mushroom sauce, roasted cauliflower',
        prepTime: '20 minutes',
        difficulty: 'Medium',
        alternatives: ['Lamb chops', 'Chicken thighs'],
      },
    ],
    snack: [
      {
        name: 'Macadamia Nuts & Cheese',
        description: '1/4 cup macadamia nuts, 50g cheddar cheese, olives',
        prepTime: '0 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Pecans with cheese', 'Brazil nuts with cheese'],
      },
      {
        name: 'Beef Jerky & Avocado',
        description: '60g grass-fed beef jerky, 1/2 avocado, sea salt',
        prepTime: '0 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Biltong', 'Pepperoni slices'],
      },
      {
        name: 'Full-Fat Greek Yogurt',
        description: '150g full-fat Greek yogurt, walnuts, MCT oil',
        prepTime: '2 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Cottage cheese', 'Heavy cream'],
      },
      {
        name: 'Pork Rinds & Guacamole',
        description: '30g pork rinds, 1/2 avocado guacamole, lime juice',
        prepTime: '2 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Cheese crisps', 'Celery with almond butter'],
      },
    ],
  },
  paleo: {
    breakfast: [
      {
        name: 'Scrambled Eggs with Bacon & Berries',
        description: '3 large eggs, 3 slices bacon, 1/2 cup blueberries, ghee',
        prepTime: '10 minutes',
        difficulty: 'Easy',
        alternatives: ['Frittata', 'Egg scramble'],
      },
      {
        name: 'Sweet Potato Hash with Sausage',
        description: '150g sweet potato hash, 2 paleo sausages, spinach, ghee',
        prepTime: '15 minutes',
        difficulty: 'Easy',
        alternatives: ['Root vegetable hash', 'Cauliflower hash'],
      },
      {
        name: 'Coconut Milk Smoothie',
        description: 'Full-fat coconut milk, banana, berries, almond butter, honey',
        prepTime: '5 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Avocado smoothie', 'Bone broth smoothie'],
      },
      {
        name: 'Grilled Fish with Fruit',
        description: '100g grilled white fish, sliced mango, raspberries, olive oil',
        prepTime: '15 minutes',
        difficulty: 'Easy',
        alternatives: ['Salmon with fruit', 'Mackerel with berries'],
      },
    ],
    lunch: [
      {
        name: 'Grilled Chicken with Roasted Root Vegetables',
        description: '150g grilled chicken breast, roasted sweet potato and carrots, olive oil',
        prepTime: '25 minutes',
        difficulty: 'Medium',
        alternatives: ['Beef with vegetables', 'Turkey with vegetables'],
      },
      {
        name: 'Salad with Grilled Steak & Olives',
        description: 'Mixed greens, 100g grilled steak, olives, avocado, olive oil dressing',
        prepTime: '20 minutes',
        difficulty: 'Easy',
        alternatives: ['Salmon salad', 'Turkey salad'],
      },
      {
        name: 'Paleo Lettuce Wrap',
        description: 'Butter lettuce wraps, 120g ground turkey, vegetables, coconut aminos',
        prepTime: '10 minutes',
        difficulty: 'Easy',
        alternatives: ['Beef lettuce wraps', 'Lamb lettuce wraps'],
      },
      {
        name: 'Baked Sweet Potato with Ground Beef',
        description: 'Large baked sweet potato, 120g lean ground beef, broccoli, ghee',
        prepTime: '30 minutes',
        difficulty: 'Easy',
        alternatives: ['Yam with beef', 'Root vegetables with beef'],
      },
    ],
    dinner: [
      {
        name: 'Grilled Salmon with Asparagus & Almonds',
        description: '150g grilled salmon, roasted asparagus, sliced almonds, olive oil',
        prepTime: '25 minutes',
        difficulty: 'Medium',
        alternatives: ['Halibut', 'Sea bass'],
      },
      {
        name: 'Slow-Cooked Beef Stew',
        description: 'Beef chuck, root vegetables, bone broth, herbs, coconut oil',
        prepTime: '120 minutes',
        difficulty: 'Medium',
        alternatives: ['Lamb stew', 'Venison stew'],
      },
      {
        name: 'Grilled Lamb Chops with Mushrooms',
        description: '2 lamb chops, sautéed mushrooms, roasted zucchini, ghee',
        prepTime: '20 minutes',
        difficulty: 'Medium',
        alternatives: ['Beef chops', 'Bison chops'],
      },
      {
        name: 'Turkey Meatballs with Vegetables',
        description: '150g turkey meatballs (coconut flour binder), roasted vegetables',
        prepTime: '25 minutes',
        difficulty: 'Medium',
        alternatives: ['Beef meatballs', 'Lamb meatballs'],
      },
    ],
    snack: [
      {
        name: 'Apple with Almond Butter',
        description: '1 medium apple, 2 tbsp almond butter, honey drizzle',
        prepTime: '2 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Banana with nut butter', 'Berries with nut butter'],
      },
      {
        name: 'Coconut & Macadamia Nuts',
        description: '1/4 cup unsweetened coconut flakes, 1/4 cup macadamia nuts',
        prepTime: '0 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Almonds with berries', 'Pecans with dates'],
      },
      {
        name: 'Homemade Paleo Bars',
        description: 'Dates, almonds, coconut oil, dark chocolate (optional)',
        prepTime: '10 minutes',
        difficulty: 'Easy',
        alternatives: ['Larabars', 'Fruit and nuts'],
      },
      {
        name: 'Beef Jerky & Berries',
        description: '60g grass-fed beef jerky, 1/2 cup mixed berries',
        prepTime: '0 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Turkey jerky', 'Biltong'],
      },
    ],
  },
  mediterranean: {
    breakfast: [
      {
        name: 'Greek Yogurt with Honey & Walnuts',
        description: '1 cup Greek yogurt, 1 tbsp honey, 1/4 cup walnuts, berries',
        prepTime: '5 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Ricotta with honey', 'Feta cheese'],
      },
      {
        name: 'Whole Grain Toast with Olive Oil & Tomatoes',
        description: '2 slices whole grain bread, olive oil, fresh tomatoes, feta, oregano',
        prepTime: '5 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Whole grain toast with avocado', 'Toast with cheese'],
      },
      {
        name: 'Mediterranean Omelet',
        description: '3 eggs, spinach, feta cheese, tomatoes, olives, olive oil',
        prepTime: '15 minutes',
        difficulty: 'Easy',
        alternatives: ['Vegetable frittata', 'Egg scramble'],
      },
      {
        name: 'Whole Grain Oatmeal with Figs & Nuts',
        description: '1 cup oatmeal, 2 dried figs, 1/4 cup almonds, honey, olive oil',
        prepTime: '15 minutes',
        difficulty: 'Easy',
        alternatives: ['Barley', 'Spelt'],
      },
    ],
    lunch: [
      {
        name: 'Grilled Fish with Olive Oil & Lemon',
        description: '150g grilled sea bass or mackerel, whole grain, roasted vegetables',
        prepTime: '25 minutes',
        difficulty: 'Medium',
        alternatives: ['Salmon', 'Halibut'],
      },
      {
        name: 'Mediterranean Chickpea Salad',
        description: '1 cup chickpeas, tomatoes, cucumber, red onion, feta, olive oil dressing',
        prepTime: '10 minutes',
        difficulty: 'Easy',
        alternatives: ['Lentil salad', 'White bean salad'],
      },
      {
        name: 'Whole Wheat Pasta with Vegetable Sauce',
        description: '1.5 cups whole wheat pasta, tomato sauce, zucchini, spinach, herbs',
        prepTime: '20 minutes',
        difficulty: 'Easy',
        alternatives: ['Farro pasta', 'Barley'],
      },
      {
        name: 'Mediterranean Wrap',
        description: 'Whole grain wrap, hummus, feta, tomatoes, cucumber, olive oil',
        prepTime: '5 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Falafel wrap', 'Vegetable wrap'],
      },
    ],
    dinner: [
      {
        name: 'Baked Salmon with Herbs & Lemon',
        description: '150g baked salmon, herbs, lemon, olive oil, roasted vegetables',
        prepTime: '30 minutes',
        difficulty: 'Medium',
        alternatives: ['Baked sea bass', 'Baked halibut'],
      },
      {
        name: 'Whole Grain Risotto with Vegetables',
        description: 'Whole grain rice, vegetable broth, spinach, tomatoes, herbs, parmesan',
        prepTime: '30 minutes',
        difficulty: 'Medium',
        alternatives: ['Farro risotto', 'Barley risotto'],
      },
      {
        name: 'Grilled Lamb with Mediterranean Salad',
        description: '120g grilled lamb, Mediterranean salad, whole grain bread, olive oil',
        prepTime: '25 minutes',
        difficulty: 'Medium',
        alternatives: ['Chicken', 'Beef'],
      },
      {
        name: 'Minestrone Soup with Whole Grain Bread',
        description: 'Vegetable soup with beans, whole grain pasta, herbs, olive oil',
        prepTime: '30 minutes',
        difficulty: 'Medium',
        alternatives: ['Lentil soup', 'White bean soup'],
      },
    ],
    snack: [
      {
        name: 'Mixed Olives & Almonds',
        description: '1/4 cup olives, 1/4 cup almonds, feta cheese',
        prepTime: '0 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Mixed nuts', 'Hummus with veggies'],
      },
      {
        name: 'Whole Grain Crackers with Hummus',
        description: '6-8 whole grain crackers, 1/4 cup hummus, lemon',
        prepTime: '2 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Whole wheat bread', 'Vegetable chips'],
      },
      {
        name: 'Greek Yogurt with Honey & Walnuts',
        description: '100g Greek yogurt, 1 tsp honey, 2 tbsp walnuts',
        prepTime: '2 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Feta cheese', 'Ricotta'],
      },
      {
        name: 'Fig & Almond Energy Balls',
        description: 'Figs, almonds, dates, olive oil, honey',
        prepTime: '10 minutes',
        difficulty: 'Easy',
        alternatives: ['Date and walnut balls', 'Apricot and nut balls'],
      },
    ],
  },
  'low-carb': {
    breakfast: [
      {
        name: 'Scrambled Eggs with Vegetables',
        description: '3 large eggs, spinach, mushrooms, tomatoes, butter, cheese',
        prepTime: '10 minutes',
        difficulty: 'Easy',
        alternatives: ['Omelet with vegetables', 'Egg muffins'],
      },
      {
        name: 'Full-Fat Greek Yogurt with Berries',
        description: '150g full-fat Greek yogurt, 1/2 cup berries, walnuts, stevia',
        prepTime: '2 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Cottage cheese', 'Cream cheese'],
      },
      {
        name: 'Smoked Salmon with Cream Cheese & Veggies',
        description: '100g smoked salmon, 50g cream cheese, cucumber, avocado',
        prepTime: '5 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Mackerel', 'Sardines'],
      },
      {
        name: 'Low-Carb Breakfast Sausage & Vegetables',
        description: '2-3 low-carb sausages, sautéed spinach and mushrooms, butter',
        prepTime: '10 minutes',
        difficulty: 'Easy',
        alternatives: ['Bacon with vegetables', 'Turkey sausage'],
      },
    ],
    lunch: [
      {
        name: 'Grilled Chicken with Roasted Vegetables',
        description: '150g grilled chicken, roasted broccoli, cauliflower, zucchini, olive oil',
        prepTime: '25 minutes',
        difficulty: 'Medium',
        alternatives: ['Beef', 'Turkey'],
      },
      {
        name: 'Cobb Salad',
        description: 'Mixed greens, bacon, hard-boiled eggs, avocado, cheese, ranch dressing',
        prepTime: '10 minutes',
        difficulty: 'Easy',
        alternatives: ['Chef salad', 'Spinach salad'],
      },
      {
        name: 'Low-Carb Lettuce Wrap Sandwich',
        description: 'Butter lettuce wraps, turkey, cheese, mayo, lettuce, tomato',
        prepTime: '5 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Beef lettuce wrap', 'Chicken lettuce wrap'],
      },
      {
        name: 'Grilled Fish with Roasted Asparagus',
        description: '150g grilled fish, roasted asparagus, lemon butter, olive oil',
        prepTime: '20 minutes',
        difficulty: 'Medium',
        alternatives: ['Salmon', 'Halibut'],
      },
    ],
    dinner: [
      {
        name: 'Ribeye Steak with Creamed Spinach',
        description: '150g grilled ribeye, creamed spinach, cauliflower mash',
        prepTime: '25 minutes',
        difficulty: 'Medium',
        alternatives: ['NY Strip', 'Filet mignon'],
      },
      {
        name: 'Baked Salmon with Hollandaise & Broccoli',
        description: '150g baked salmon, hollandaise, steamed broccoli, lemon',
        prepTime: '25 minutes',
        difficulty: 'Medium',
        alternatives: ['Halibut', 'Sea bass'],
      },
      {
        name: 'Ground Turkey Taco Bowl (No Rice)',
        description: '150g ground turkey, salsa, cheese, avocado, lettuce, sour cream',
        prepTime: '10 minutes',
        difficulty: 'Easy',
        alternatives: ['Beef taco bowl', 'Chicken taco bowl'],
      },
      {
        name: 'Pork Chops with Garlic Butter & Vegetables',
        description: '2 pork chops, garlic butter, roasted zucchini and mushrooms',
        prepTime: '20 minutes',
        difficulty: 'Medium',
        alternatives: ['Lamb chops', 'Chicken thighs'],
      },
    ],
    snack: [
      {
        name: 'Cheese & Nuts',
        description: '50g cheddar or your favorite cheese, 1/4 cup almonds or pecans',
        prepTime: '0 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Cheese and olives', 'Cheese and salami'],
      },
      {
        name: 'Celery with Almond Butter',
        description: 'Celery stalks, 2 tbsp almond butter, optional bacon bits',
        prepTime: '2 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Cucumber with dip', 'Bell pepper with guacamole'],
      },
      {
        name: 'Hard-Boiled Eggs',
        description: '2-3 hard-boiled eggs, salt, pepper, optional mayo',
        prepTime: '10 minutes (if prepared)',
        difficulty: 'Very Easy',
        alternatives: ['Deviled eggs', 'Egg salad'],
      },
      {
        name: 'Pepperoni & Cheese Slices',
        description: '1 oz pepperoni, 1 oz cheese (mozzarella or cheddar)',
        prepTime: '0 minutes',
        difficulty: 'Very Easy',
        alternatives: ['Salami and cheese', 'Prosciutto and cheese'],
      },
    ],
  },
};

const trMeals = {
  omnivore: {
    breakfast: [
      {
        name: 'Avokadolu Çırpılmış Yumurta Tost',
        description: '3 büyük yumurta, 2 dilim tam buğday ekmeği, 1/2 avokado, 1 portakal',
        prepTime: '10 dakika',
        difficulty: 'Easy',
        alternatives: ['Meyveli ve fındıklı yulaf', 'Granolalı Yunan yoğurdu'],
      },
      {
        name: 'Meyveli & Bademli Yulaf Ezmesi',
        description: '1 su bardağı yulaf, 1 muz, 1/2 su bardağı yaban mersini, 1/4 su bardağı badem, bal',
        prepTime: '15 dakika',
        difficulty: 'Easy',
        alternatives: ['Sağlıklı bekonlu krep', 'Protein tozlu smoothie'],
      },
      {
        name: 'Yunan Yoğurtlu Parfait',
        description: '1.5 su bardağı Yunan yoğurdu, 1/2 su bardağı granola, 1/2 su bardağı karışık meyve, bal',
        prepTime: '5 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Meyveli lor peyniri', 'Protein smoothie'],
      },
      {
        name: 'Tavuk Sosisli Kahvaltı',
        description: '2 tavuk sosisi, 2 dilim tam buğday ekmeği, 1 yemek kaşığı badem ezmesi, meyveler',
        prepTime: '10 dakika',
        difficulty: 'Easy',
        alternatives: ['Bekon ve yumurta', 'Hindi sosisi'],
      },
    ],
    lunch: [
      {
        name: 'Pirinç & Brokoli ile Izgara Tavuk Göğsü',
        description: '150g ızgara tavuk göğsü, 150g esmer pirinç, 150g buharda brokoli, zeytinyağı',
        prepTime: '20 dakika',
        difficulty: 'Medium',
        alternatives: ['Tatlı patatestli hindi', 'Pirinçli somon'],
      },
      {
        name: 'Hindi & Sebzeli Dürüm',
        description: 'Tam buğday dürüm, 100g dilimlenmiş hindi eti, marul, domates, humus, avokado',
        prepTime: '5 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Tavuklu dürüm', 'Ton balıklı dürüm'],
      },
      {
        name: 'Tatlı Patates & Kuşkonmaz ile Somon',
        description: '150g fırında somon, 150g tatlı patates, 150g buharda kuşkonmaz, limon',
        prepTime: '25 dakika',
        difficulty: 'Medium',
        alternatives: ['Patatesli morina', 'Sebzeli pisi balığı'],
      },
      {
        name: 'Makarna & Domates Sos ile Yağsız Dana Kıyma',
        description: '120g yağsız dana kıyma, 1.5 su bardağı tam buğday makarna, domates sosu, sebzeler',
        prepTime: '20 dakika',
        difficulty: 'Medium',
        alternatives: ['Hindi köftesi', 'Tavuklu makarna'],
      },
    ],
    dinner: [
      {
        name: 'Kızarmış Sebzeli Izgara Biftek',
        description: '150g ızgara biftek (yağsız kesim), kızarmış brokoli ve havuç, tatlı patates',
        prepTime: '30 dakika',
        difficulty: 'Medium',
        alternatives: ['Izgara tavuk', 'Fırında balık'],
      },
      {
        name: 'Kinoa & Taze Fasulye ile Fırında Tavuk',
        description: '150g fırında tavuk göğsü, 150g kinoa, 150g buharda taze fasulye, zeytinyağı',
        prepTime: '30 dakika',
        difficulty: 'Easy',
        alternatives: ['Hindi göğsü', 'Fırında balık'],
      },
      {
        name: 'Lahanali Balık Takosu',
        description: '150g fırında beyaz balık, 2 tam tahıl tortilla, lahana salatası, limon, kişniş',
        prepTime: '20 dakika',
        difficulty: 'Medium',
        alternatives: ['Tavuklu tako', 'Karidesli tako'],
      },
      {
        name: 'Kızarmış Kök Sebzeli Domuz Filetosu',
        description: '150g fırında domuz filetosu, kızarmış tatlı patates ve brüksel lahanası',
        prepTime: '35 dakika',
        difficulty: 'Medium',
        alternatives: ['Dana fileto', 'Tavuk göğsü'],
      },
    ],
    snack: [
      {
        name: 'Protein Shake',
        description: 'Protein tozu, muz, 1 yemek kaşığı fıstık ezmesi, badem sütü, buz',
        prepTime: '5 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Yunan yoğurdu', 'Protein bar'],
      },
      {
        name: 'Badem & Kuru Meyve Karışımı',
        description: '1/4 su bardağı badem, 2 yemek kaşığı kuru kızılcık, 2 yemek kaşığı kuru üzüm',
        prepTime: '0 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Karışık kuruyemiş', 'Trail mix'],
      },
      {
        name: 'Meyveli Lor Peyniri',
        description: '150g az yağlı lor peyniri, 1/2 su bardağı karışık meyve, 1 yemek kaşığı bal',
        prepTime: '2 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Yunan yoğurdu', 'Protein puding'],
      },
      {
        name: 'Bademli Elma',
        description: '1 orta boy elma, 2 yemek kaşığı badem ezmesi',
        prepTime: '2 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Fıstık ezmeli muz', 'Pirinç keki'],
      },
    ],
  },
  vegetarian: {
    breakfast: [
      {
        name: 'Avokadolu Çırpılmış Yumurta Tost',
        description: '3 büyük yumurta, 2 dilim tam buğday ekmeği, 1/2 avokado, 1 portakal',
        prepTime: '10 dakika',
        difficulty: 'Easy',
        alternatives: ['Protein tozlu yulaf', 'Granolalı Yunan yoğurdu'],
      },
      {
        name: 'Mantarlı Tofu Karışımı',
        description: '150g sert tofu, mantar, ıspanak, soğan, 2 dilim ekmek, zeytinyağı',
        prepTime: '15 dakika',
        difficulty: 'Medium',
        alternatives: ['Sebzeli frittata', 'Nohutlu karışım'],
      },
      {
        name: 'Yunan Yoğurtlu Parfait',
        description: '1.5 su bardağı Yunan yoğurdu, 1/2 su bardağı granola, 1/2 su bardağı meyve, bal',
        prepTime: '5 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Lor peynirli parfait', 'Bitkisel yoğurt'],
      },
      {
        name: 'Lor Peynirli Krep',
        description: '1 su bardağı lor peyniri yumurta ile karıştırılmış, tam tahıl unu, üzerinde meyveler',
        prepTime: '15 dakika',
        difficulty: 'Medium',
        alternatives: ['Yulaf ezmeli krep', 'Protein krepi'],
      },
    ],
    lunch: [
      {
        name: 'Nohut & Kinoa Salatası',
        description: '1 su bardağı pişmiş nohut, 1 su bardağı kinoa, sebzeler, tahin sosu, limon',
        prepTime: '15 dakika',
        difficulty: 'Easy',
        alternatives: ['Mercimek salatası', 'Fasulye & tahıl kasesi'],
      },
      {
        name: 'Tatlı Patates Kızartmalı Sebze Burgeri',
        description: 'Sebze burgeri, tam tahıl sandviç ekmeği, tatlı patates kızartması, sebzeler',
        prepTime: '20 dakika',
        difficulty: 'Easy',
        alternatives: ['Siyah fasulye burgeri', 'Falafel dürüm'],
      },
      {
        name: 'Tam Tahıl Ekmekli Mercimek Çorbası',
        description: '1 porsiyon mercimek çorbası, 1 dilim tam tahıl ekmeği ve humus, yan salata',
        prepTime: '10 dakika (hazırlanmışsa)',
        difficulty: 'Easy',
        alternatives: ['Fasulye çorbası', 'Sebze çorbası'],
      },
      {
        name: 'Nohutlu & Beyaz Peynirli Yunan Salatası',
        description: 'Karışık yeşillik, nohut, beyaz peynir, zeytin, salatalık, domates, zeytinyağı',
        prepTime: '10 dakika',
        difficulty: 'Easy',
        alternatives: ['Caprese salatası', 'Akdeniz salatası'],
      },
    ],
    dinner: [
      {
        name: 'Kızarmış Sebzeli & Pirinçli Fırında Tofu',
        description: '200g marine edilmiş fırında tofu, kızarmış brokoli ve havuç, 1 su bardağı esmer pirinç',
        prepTime: '30 dakika',
        difficulty: 'Medium',
        alternatives: ['Tempeh karışık', 'Seitan sebzeli'],
      },
      {
        name: 'Mercimek & Sebze Körisi Pirinç ile',
        description: '1.5 su bardağı pişmiş mercimek, köri sosu, sebzeler, 1 su bardağı esmer pirinç',
        prepTime: '30 dakika',
        difficulty: 'Medium',
        alternatives: ['Nohut körisi', 'Fasulye körisi'],
      },
      {
        name: 'Kaju & Kinoa ile Sebze Woku',
        description: 'Karışık sebzeler, 1/4 su bardağı kaju, 1 su bardağı kinoa, soya-zencefil sosu',
        prepTime: '20 dakika',
        difficulty: 'Easy',
        alternatives: ['Tofulu wok', 'Tempehli wok'],
      },
      {
        name: 'Nohut Makarna Marinara & Yeşillikler ile',
        description: '1.5 su bardağı tam buğday makarna, nohut bazlı makarna, marinara sosu, ıspanak',
        prepTime: '20 dakika',
        difficulty: 'Easy',
        alternatives: ['Mercimek makarnası', 'Fasulye makarnası'],
      },
    ],
    snack: [
      {
        name: 'Protein Shake',
        description: 'Bitkisel protein tozu, muz, badem ezmesi, badem sütü',
        prepTime: '5 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Bitkisel yoğurt', 'Protein bar'],
      },
      {
        name: 'Karışık Kuruyemiş & Tohum',
        description: '1/4 su bardağı badem, kaju, kabak çekirdeği, ayçiçek çekirdeği',
        prepTime: '0 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Trail mix', 'Krakerli fıstık ezmesi'],
      },
      {
        name: 'Sebze Çubuklu Humus',
        description: '1/4 su bardağı humus, havuç, kereviz, biber',
        prepTime: '5 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Sebzeli guacamole', 'Tahin sosu'],
      },
      {
        name: 'Granolalı Yunan Yoğurdu',
        description: '150g Yunan yoğurdu, 1/4 su bardağı granola, meyveler',
        prepTime: '2 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Lor peyniri', 'Bitkisel yoğurt'],
      },
    ],
  },
  vegan: {
    breakfast: [
      {
        name: 'Bitkisel Protein & Meyveli Yulaf Ezmesi',
        description: '1 su bardağı yulaf, bitkisel protein tozu, karışık meyve, badem sütü, bal',
        prepTime: '15 dakika',
        difficulty: 'Easy',
        alternatives: ['Smoothie kasesi', 'Tofu karışımı'],
      },
      {
        name: 'Mantarlı & Ekmekli Tofu Karışımı',
        description: '150g sert tofu, mantar, ıspanak, 2 dilim tam tahıl ekmeği, zeytinyağı',
        prepTime: '15 dakika',
        difficulty: 'Medium',
        alternatives: ['Nohutlu karışım', 'Tempehli karışım'],
      },
      {
        name: 'Smoothie Kasesi',
        description: 'Blendırlanmış muz, meyveler, bitkisel süt, üzerinde granola, hindistan cevizi, tohumlar',
        prepTime: '10 dakika',
        difficulty: 'Easy',
        alternatives: ['Açai kasesi', 'Yeşil smoothie kasesi'],
      },
      {
        name: 'Meyveli Chia Tohumu Pudingi',
        description: 'Chia tohumları, badem sütü, akçaağaç şurubu, taze meyve, granola',
        prepTime: '5 dakika (+ bir gece)',
        difficulty: 'Very Easy',
        alternatives: ['Kenevir tohumu pudingi', 'Keten tohumu pudingi'],
      },
    ],
    lunch: [
      {
        name: 'Nohut & Sebze Körisi Pirinç ile',
        description: '1 su bardağı pişmiş nohut, köri sosu, sebzeler, 1 su bardağı esmer pirinç',
        prepTime: '25 dakika',
        difficulty: 'Medium',
        alternatives: ['Mercimek körisi', 'Tofu körisi'],
      },
      {
        name: 'Mercimek & Cevizli Taco',
        description: 'Baharatlı pişmiş mercimek, ceviz, tam tahıl tortilla, salsa, marul',
        prepTime: '15 dakika',
        difficulty: 'Easy',
        alternatives: ['Siyah fasulye taco', 'Tofu taco'],
      },
      {
        name: 'Tempeh & Sebze Wofu Kinoa ile',
        description: '150g marine edilmiş tempeh, karışık sebzeler, kinoa, soya-zencefil sosu',
        prepTime: '20 dakika',
        difficulty: 'Medium',
        alternatives: ['Tofulu wok', 'Seitan wok'],
      },
      {
        name: 'Kızarmış Sebzeli Humuslu Dürüm',
        description: 'Tam tahıl dürüm, humus, kızarmış sebzeler, tahin sosu',
        prepTime: '15 dakika',
        difficulty: 'Easy',
        alternatives: ['Falafel dürüm', 'Tofu dürüm'],
      },
    ],
    dinner: [
      {
        name: "Kızarmış Sebzeli & Farro'lu Fırında Tofu",
        description: '200g marine edilmiş fırında tofu, kızarmış brokoli, farro, limon-ot sosu',
        prepTime: '30 dakika',
        difficulty: 'Medium',
        alternatives: ['Tempeh', 'Seitan'],
      },
      {
        name: 'Tam Buğday Makarnalı Mercimek Bolognese',
        description: '1.5 su bardağı pişmiş mercimek, marinara sosu, 1.5 su bardağı makarna, buharda ıspanak',
        prepTime: '25 dakika',
        difficulty: 'Medium',
        alternatives: ['Mantarlı bolognese', 'Nohutlu bolognese'],
      },
      {
        name: 'Sebze & Siyah Fasulye Enchiladası',
        description: 'Tam tahıl tortilla, siyah fasulye, sebzeler, salsa, kaju kreması sosu',
        prepTime: '30 dakika',
        difficulty: 'Medium',
        alternatives: ['Nohutlu enchilada', 'Fasulye enchiladası'],
      },
      {
        name: 'Nohut & Ispanaklı Köri Hindistan Cevizi Pirinci ile',
        description: '1 su bardağı nohut, ıspanak, hindistan cevizi körisi, hindistan cevizi pirinci',
        prepTime: '25 dakika',
        difficulty: 'Medium',
        alternatives: ['Tofu körisi', 'Mercimek körisi'],
      },
    ],
    snack: [
      {
        name: 'Vegan Protein Shake',
        description: 'Bitkisel protein tozu, muz, badem ezmesi, badem sütü, buz',
        prepTime: '5 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Fındıklı smoothie', 'Bitkisel yoğurt'],
      },
      {
        name: 'Karışık Kuruyemiş & Tohum',
        description: '1/4 su bardağı badem, kaju, kabak çekirdeği, ayçiçek çekirdeği',
        prepTime: '0 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Trail mix', 'Meyveli fıstık ezmesi'],
      },
      {
        name: 'Meyveli Hindistan Cevizi Yoğurdu',
        description: '150g hindistan cevizi yoğurdu, 1/2 su bardağı karışık meyve, 1 yemek kaşığı bal/akçaağaç şurubu',
        prepTime: '2 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Badem yoğurdu', 'Yulaf yoğurdu'],
      },
      {
        name: 'Bademli Meyve',
        description: 'Elma veya muz, 2 yemek kaşığı badem ezmesi',
        prepTime: '2 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Meyveli tahin', 'Meyveli kaju ezmesi'],
      },
    ],
  },
  keto: {
    breakfast: [
      {
        name: 'Bekon & Avokadolu Çırpılmış Yumurta',
        description: '4 büyük yumurta, 3 dilim bekon, 1/2 avokado, tereyağı',
        prepTime: '10 dakika',
        difficulty: 'Easy',
        alternatives: ['Yumurta muffin', 'Peynirli omlet'],
      },
      {
        name: 'Fındıklı & Tohumlu Yunan Yoğurdu',
        description: '150g tam yağlı Yunan yoğurdu, 1/4 su bardağı kuruyemiş, 2 yemek kaşığı tohum, MCT yağı',
        prepTime: '2 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Lor peyniri', 'Meyveli krema'],
      },
      {
        name: 'Krem Peynirli Füme Somon',
        description: '100g füme somon, 50g krem peynir, salatalık dilimleri, kapari',
        prepTime: '5 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Avokadolu uskumru', 'Krem peynirli sardalya'],
      },
      {
        name: 'MCT Yağlı Tereyağlı Kahve',
        description: 'Siyah kahve, 1 yemek kaşığı tereyağı, 1 yemek kaşığı MCT yağı, bir tutam tuz',
        prepTime: '5 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Kurşun geçirmez kahve', 'Kremalı kahve'],
      },
    ],
    lunch: [
      {
        name: 'Tereyağı & Sebzeli Izgara Ribeye',
        description: '150g ızgara ribeye, sarımsaklı tereyağı, buharda brokoli ve kabak',
        prepTime: '25 dakika',
        difficulty: 'Medium',
        alternatives: ['Somon', 'Kuzu pirzolası'],
      },
      {
        name: 'Ton Balığı Salatası Marullara Sarılmış',
        description: '150g konserve ton balığı (yağda), mayonez, kereviz, tereyağı marulu',
        prepTime: '5 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Tavuk salatası', 'Yumurta salatası'],
      },
      {
        name: 'Bekon & Peynirli Hamburger (Ekmezsiz)',
        description: '150g dana burger köftesi, 2 dilim peynir, bekon, mayonez, turşu',
        prepTime: '10 dakika',
        difficulty: 'Easy',
        alternatives: ['Hindi burgeri', 'Kuzu burgeri'],
      },
      {
        name: 'Zeytinyağlı Caprese Salatası',
        description: 'Taze mozzarella, domates, fesleğen, zeytinyağı, az balzamik sirke',
        prepTime: '5 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Bekonlu ıspanak salatası', 'Zeytinyağlı kale salatası'],
      },
    ],
    dinner: [
      {
        name: 'Hollandaise Soslu Izgara Somon',
        description: '150g ızgara somon, hollandaise sosu, kızarmış kuşkonmaz',
        prepTime: '25 dakika',
        difficulty: 'Medium',
        alternatives: ['Tereyağlı pisi balığı', 'Hollandaise soslu morina'],
      },
      {
        name: 'Ot Tereyağlı Ribeye Biftek',
        description: '200g ızgara ribeye, ot bileşik tereyağı, kızarmış brüksel lahanası',
        prepTime: '25 dakika',
        difficulty: 'Medium',
        alternatives: ['NY Strip', 'Fileto mignon'],
      },
      {
        name: 'Kabak Eriştelı Karides Scampi',
        description: '200g karides, sarımsaklı tereyağı, kabak erişte, limon, maydanoz',
        prepTime: '15 dakika',
        difficulty: 'Easy',
        alternatives: ['Deniz tarağı', 'Istakoz'],
      },
      {
        name: 'Kremalı Mantar Soslu Domuz Pirzolası',
        description: '2 domuz pirzolası, ağır krema mantar sosu, kızarmış karnabahar',
        prepTime: '20 dakika',
        difficulty: 'Medium',
        alternatives: ['Kuzu pirzolası', 'Tavuk budu'],
      },
    ],
    snack: [
      {
        name: 'Macadamia Fıstığı & Peynir',
        description: '1/4 su bardağı macadamia fıstığı, 50g çedar peyniri, zeytin',
        prepTime: '0 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Pekanlı peynir', 'Brezilya fıstıklı peynir'],
      },
      {
        name: 'Dana Jerky & Avokado',
        description: '60g otla beslenen dana jerky, 1/2 avokado, deniz tuzu',
        prepTime: '0 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Biltong', 'Pepperoni dilimleri'],
      },
      {
        name: 'Tam Yağlı Yunan Yoğurdu',
        description: '150g tam yağlı Yunan yoğurdu, ceviz, MCT yağı',
        prepTime: '2 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Lor peyniri', 'Ağır krema'],
      },
      {
        name: 'Domuz Kabuğu & Guacamole',
        description: '30g domuz kabuğu, 1/2 avokado guacamole, limon suyu',
        prepTime: '2 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Peynir cipsi', 'Bademli kereviz'],
      },
    ],
  },
  paleo: {
    breakfast: [
      {
        name: 'Bekon & Meyveli Çırpılmış Yumurta',
        description: '3 büyük yumurta, 3 dilim bekon, 1/2 su bardağı yaban mersini, sade yağ',
        prepTime: '10 dakika',
        difficulty: 'Easy',
        alternatives: ['Frittata', 'Yumurta karışımı'],
      },
      {
        name: 'Sosisli Tatlı Patates Kavurması',
        description: '150g tatlı patates kavurması, 2 paleo sosisi, ıspanak, sade yağ',
        prepTime: '15 dakika',
        difficulty: 'Easy',
        alternatives: ['Kök sebze kavurması', 'Karnabahar kavurması'],
      },
      {
        name: 'Hindistan Cevizi Sütlü Smoothie',
        description: 'Tam yağlı hindistan cevizi sütü, muz, meyveler, badem ezmesi, bal',
        prepTime: '5 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Avokadolu smoothie', 'Kemik suyu smoothie'],
      },
      {
        name: 'Meyveli Izgara Balık',
        description: '100g ızgara beyaz balık, dilimlenmiş mango, ahududu, zeytinyağı',
        prepTime: '15 dakika',
        difficulty: 'Easy',
        alternatives: ['Meyveli somon', 'Meyveli uskumru'],
      },
    ],
    lunch: [
      {
        name: 'Kızarmış Kök Sebzeli Izgara Tavuk',
        description: '150g ızgara tavuk göğsü, kızarmış tatlı patates ve havuç, zeytinyağı',
        prepTime: '25 dakika',
        difficulty: 'Medium',
        alternatives: ['Sebzeli dana eti', 'Sebzeli hindi'],
      },
      {
        name: 'Izgara Biftek & Zeytinli Salata',
        description: 'Karışık yeşillik, 100g ızgara biftek, zeytin, avokado, zeytinyağı sosu',
        prepTime: '20 dakika',
        difficulty: 'Easy',
        alternatives: ['Somonlu salata', 'Hindili salata'],
      },
      {
        name: 'Paleo Marul Sarması',
        description: 'Tereyağı marulu sarması, 120g öğütülmüş hindi, sebzeler, hindistan cevizi aroması',
        prepTime: '10 dakika',
        difficulty: 'Easy',
        alternatives: ['Dana etli marul sarması', 'Kuzu etli marul sarması'],
      },
      {
        name: 'Kıymalı Fırında Tatlı Patates',
        description: 'Büyük fırında tatlı patates, 120g yağsız dana kıyma, brokoli, sade yağ',
        prepTime: '30 dakika',
        difficulty: 'Easy',
        alternatives: ['Dana etli yam', 'Dana etli kök sebze'],
      },
    ],
    dinner: [
      {
        name: 'Kuşkonmaz & Bademli Izgara Somon',
        description: '150g ızgara somon, kızarmış kuşkonmaz, dilimlenmiş badem, zeytinyağı',
        prepTime: '25 dakika',
        difficulty: 'Medium',
        alternatives: ['Pisi balığı', 'Levrek'],
      },
      {
        name: 'Yavaş Pişirilmiş Dana Yahnisi',
        description: 'Dana kaburga, kök sebzeler, kemik suyu, otlar, hindistan cevizi yağı',
        prepTime: '120 dakika',
        difficulty: 'Medium',
        alternatives: ['Kuzu yahnisi', 'Geyik yahnisi'],
      },
      {
        name: 'Mantarlı Izgara Kuzu Pirzolası',
        description: '2 kuzu pirzolası, sote mantar, kızarmış kabak, sade yağ',
        prepTime: '20 dakika',
        difficulty: 'Medium',
        alternatives: ['Dana pirzolası', 'Bizon pirzolası'],
      },
      {
        name: 'Sebzeli Hindi Köftesi',
        description: '150g hindi köftesi (hindistan cevizi unu ile), kızarmış sebzeler',
        prepTime: '25 dakika',
        difficulty: 'Medium',
        alternatives: ['Dana köftesi', 'Kuzu köftesi'],
      },
    ],
    snack: [
      {
        name: 'Bademli Elma',
        description: '1 orta boy elma, 2 yemek kaşığı badem ezmesi, bal',
        prepTime: '2 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Fıstık ezmeli muz', 'Meyveli fıstık ezmesi'],
      },
      {
        name: 'Hindistan Cevizi & Macadamia Fıstığı',
        description: '1/4 su bardağı şekersiz hindistan cevizi cipsi, 1/4 su bardağı macadamia fıstığı',
        prepTime: '0 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Meyveli badem', 'Hurmalı pekan'],
      },
      {
        name: 'Ev Yapımı Paleo Bar',
        description: 'Hurma, badem, hindistan cevizi yağı, bitter çikolata (isteğe bağlı)',
        prepTime: '10 dakika',
        difficulty: 'Easy',
        alternatives: ['Larabar', 'Meyve ve kuruyemiş'],
      },
      {
        name: 'Dana Jerky & Meyveler',
        description: '60g otla beslenen dana jerky, 1/2 su bardağı karışık meyve',
        prepTime: '0 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Hindi jerky', 'Biltong'],
      },
    ],
  },
  mediterranean: {
    breakfast: [
      {
        name: 'Bal & Cevizli Yunan Yoğurdu',
        description: '1 su bardağı Yunan yoğurdu, 1 yemek kaşığı bal, 1/4 su bardağı ceviz, meyveler',
        prepTime: '5 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Ballı ricotta', 'Beyaz peynir'],
      },
      {
        name: 'Zeytinyağı & Domatesli Tam Tahıl Ekmeği',
        description: '2 dilim tam tahıl ekmeği, zeytinyağı, taze domates, beyaz peynir, kekik',
        prepTime: '5 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Avokadolu tam tahıl ekmeği', 'Peynirli ekmek'],
      },
      {
        name: 'Akdeniz Omleti',
        description: '3 yumurta, ıspanak, beyaz peynir, domates, zeytin, zeytinyağı',
        prepTime: '15 dakika',
        difficulty: 'Easy',
        alternatives: ['Sebzeli frittata', 'Yumurta karışımı'],
      },
      {
        name: 'İncir & Fındıklı Tam Tahıl Yulaf Ezmesi',
        description: '1 su bardağı yulaf, 2 kuru incir, 1/4 su bardağı badem, bal, zeytinyağı',
        prepTime: '15 dakika',
        difficulty: 'Easy',
        alternatives: ['Arpa', 'Spelt'],
      },
    ],
    lunch: [
      {
        name: 'Zeytinyağı & Limonlu Izgara Balık',
        description: '150g ızgara levrek veya uskumru, tam tahıl, kızarmış sebzeler',
        prepTime: '25 dakika',
        difficulty: 'Medium',
        alternatives: ['Somon', 'Pisi balığı'],
      },
      {
        name: 'Akdeniz Nohut Salatası',
        description: '1 su bardağı nohut, domates, salatalık, kırmızı soğan, beyaz peynir, zeytinyağı sosu',
        prepTime: '10 dakika',
        difficulty: 'Easy',
        alternatives: ['Mercimek salatası', 'Beyaz fasulye salatası'],
      },
      {
        name: 'Sebze Soslu Tam Buğday Makarna',
        description: '1.5 su bardağı tam buğday makarna, domates sosu, kabak, ıspanak, otlar',
        prepTime: '20 dakika',
        difficulty: 'Easy',
        alternatives: ['Farro makarnası', 'Arpa'],
      },
      {
        name: 'Akdeniz Dürümü',
        description: 'Tam tahıl dürüm, humus, beyaz peynir, domates, salatalık, zeytinyağı',
        prepTime: '5 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Falafel dürüm', 'Sebze dürümü'],
      },
    ],
    dinner: [
      {
        name: 'Otlar & Limonlu Fırında Somon',
        description: '150g fırında somon, otlar, limon, zeytinyağı, kızarmış sebzeler',
        prepTime: '30 dakika',
        difficulty: 'Medium',
        alternatives: ['Fırında levrek', 'Fırında pisi balığı'],
      },
      {
        name: 'Sebzeli Tam Tahıl Risotto',
        description: 'Tam tahıllı pirinç, sebze suyu, ıspanak, domates, otlar, parmesan',
        prepTime: '30 dakika',
        difficulty: 'Medium',
        alternatives: ['Farro risotto', 'Arpa risotto'],
      },
      {
        name: 'Akdeniz Salatalı Izgara Kuzu',
        description: '120g ızgara kuzu, Akdeniz salatası, tam tahıl ekmeği, zeytinyağı',
        prepTime: '25 dakika',
        difficulty: 'Medium',
        alternatives: ['Tavuk', 'Dana eti'],
      },
      {
        name: 'Tam Tahıl Ekmekli Minestrone Çorbası',
        description: 'Fasulye, tam tahıl makarna, otlar, zeytinyağı ile sebze çorbası',
        prepTime: '30 dakika',
        difficulty: 'Medium',
        alternatives: ['Mercimek çorbası', 'Beyaz fasulye çorbası'],
      },
    ],
    snack: [
      {
        name: 'Karışık Zeytin & Badem',
        description: '1/4 su bardağı zeytin, 1/4 su bardağı badem, beyaz peynir',
        prepTime: '0 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Karışık kuruyemiş', 'Sebzeli humus'],
      },
      {
        name: 'Humuslu Tam Tahıl Kraker',
        description: '6-8 tam tahıl kraker, 1/4 su bardağı humus, limon',
        prepTime: '2 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Tam buğday ekmeği', 'Sebze cipsi'],
      },
      {
        name: 'Bal & Cevizli Yunan Yoğurdu',
        description: '100g Yunan yoğurdu, 1 tatlı kaşığı bal, 2 yemek kaşığı ceviz',
        prepTime: '2 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Beyaz peynir', 'Ricotta'],
      },
      {
        name: 'İncir & Badem Enerji Topu',
        description: 'İncir, badem, hurma, zeytinyağı, bal',
        prepTime: '10 dakika',
        difficulty: 'Easy',
        alternatives: ['Hurmalı ve cevizli top', 'Kayısılı ve fındıklı top'],
      },
    ],
  },
  'low-carb': {
    breakfast: [
      {
        name: 'Sebzeli Çırpılmış Yumurta',
        description: '3 büyük yumurta, ıspanak, mantar, domates, tereyağı, peynir',
        prepTime: '10 dakika',
        difficulty: 'Easy',
        alternatives: ['Sebzeli omlet', 'Yumurta muffin'],
      },
      {
        name: 'Meyveli Tam Yağlı Yunan Yoğurdu',
        description: '150g tam yağlı Yunan yoğurdu, 1/2 su bardağı meyve, ceviz, stevia',
        prepTime: '2 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Lor peyniri', 'Krem peynir'],
      },
      {
        name: 'Krem Peynir & Sebzeli Füme Somon',
        description: '100g füme somon, 50g krem peynir, salatalık, avokado',
        prepTime: '5 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Uskumru', 'Sardalya'],
      },
      {
        name: 'Düşük Karbonhidratlı Sosis & Sebzeler',
        description: '2-3 düşük karbonhidrat sosis, sote ıspanak ve mantar, tereyağı',
        prepTime: '10 dakika',
        difficulty: 'Easy',
        alternatives: ['Bekon ile sebzeler', 'Hindi sosisi'],
      },
    ],
    lunch: [
      {
        name: 'Kızarmış Sebzeli Izgara Tavuk',
        description: '150g ızgara tavuk, kızarmış brokoli, karnabahar, kabak, zeytinyağı',
        prepTime: '25 dakika',
        difficulty: 'Medium',
        alternatives: ['Dana eti', 'Hindi'],
      },
      {
        name: 'Cobb Salatası',
        description: 'Karışık yeşillik, bekon, haşlanmış yumurta, avokado, peynir, ranch sosu',
        prepTime: '10 dakika',
        difficulty: 'Easy',
        alternatives: ['Şef salatası', 'Ispanak salatası'],
      },
      {
        name: 'Düşük Karbonhidratlı Marullı Sandviç',
        description: 'Tereyağı marulu sarması, hindi, peynir, mayonez, marul, domates',
        prepTime: '5 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Dana etli marul sarması', 'Tavuklu marul sarması'],
      },
      {
        name: 'Kızarmış Kuşkonmazlı Izgara Balık',
        description: '150g ızgara balık, kızarmış kuşkonmaz, limon tereyağı, zeytinyağı',
        prepTime: '20 dakika',
        difficulty: 'Medium',
        alternatives: ['Somon', 'Pisi balığı'],
      },
    ],
    dinner: [
      {
        name: 'Kremalı Ispanaklı Ribeye Biftek',
        description: '150g ızgara ribeye, kremalı ıspanak, karnabahar püresi',
        prepTime: '25 dakika',
        difficulty: 'Medium',
        alternatives: ['NY Strip', 'Fileto mignon'],
      },
      {
        name: 'Hollandaise & Brokoli ile Fırında Somon',
        description: '150g fırında somon, hollandaise sosu, buharda brokoli, limon',
        prepTime: '25 dakika',
        difficulty: 'Medium',
        alternatives: ['Pisi balığı', 'Levrek'],
      },
      {
        name: 'Kıymalı Hindi Taco Kasesi (Pirinsiz)',
        description: '150g kıymalı hindi, salsa, peynir, avokado, marul, ekşi krema',
        prepTime: '10 dakika',
        difficulty: 'Easy',
        alternatives: ['Dana kıymalı taco kasesi', 'Tavuklu taco kasesi'],
      },
      {
        name: 'Sarımsaklı Tereyağlı & Sebzeli Domuz Pirzolası',
        description: '2 domuz pirzolası, sarımsaklı tereyağı, kızarmış kabak ve mantar',
        prepTime: '20 dakika',
        difficulty: 'Medium',
        alternatives: ['Kuzu pirzolası', 'Tavuk budu'],
      },
    ],
    snack: [
      {
        name: 'Peynir & Kuruyemiş',
        description: '50g çedar veya tercih ettiğiniz peynir, 1/4 su bardağı badem veya pekan',
        prepTime: '0 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Peynir ve zeytin', 'Peynir ve salam'],
      },
      {
        name: 'Bademli Kereviz',
        description: 'Kereviz sapları, 2 yemek kaşığı badem ezmesi, isteğe bağlı bekon kırıntıları',
        prepTime: '2 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Soslu salatalık', 'Guacamoleli biber'],
      },
      {
        name: 'Haşlanmış Yumurta',
        description: '2-3 haşlanmış yumurta, tuz, karabiber, isteğe bağlı mayonez',
        prepTime: '10 dakika (hazırlanmışsa)',
        difficulty: 'Very Easy',
        alternatives: ['Doldurulmuş yumurta', 'Yumurta salatası'],
      },
      {
        name: 'Pepperoni & Peynir Dilimleri',
        description: '30g pepperoni, 30g peynir (mozzarella veya çedar)',
        prepTime: '0 dakika',
        difficulty: 'Very Easy',
        alternatives: ['Salam ve peynir', 'Prosciutto ve peynir'],
      },
    ],
  },
};

const en = {
  timing: {
    breakfast: 'Within 1 hour of waking',
    lunch: 'Around midday (12-1pm)',
    dinner: 'Evening (6-8pm)',
    snackWorkout: 'Pre or post-workout',
    snackRest: 'Mid-afternoon or evening',
    asNeeded: 'As needed',
  },
  fallbackMeal: {
    name: 'Flexible meal (your choice)',
    description:
      'Your allergy filters exclude all of our options for this meal. Pick any meal you tolerate that roughly matches the calorie and macro targets shown.',
  },
  advice: {
    'build-muscle': [
      `Focus on progressive overload — add 1-2 reps or 5-10 lbs weekly. Sleep 7-9 hours daily. Consistency beats intensity. Track your lifts.`,
      `Prioritize compound movements. Don't chase the pump; focus on strength and volume. Quality form prevents injury and maximizes gains.`,
      `Eat protein with every meal (1.6-2.2g per kg). A surplus is essential, but don't overeat — aim for 0.5-1 lb/week weight gain.`,
    ],
    'lose-weight': [
      `Maintain a moderate deficit (-300-500 cal). Too aggressive causes muscle loss and metabolic adaptation. Target 0.5-1 lb/week loss.`,
      `Prioritize protein to preserve muscle during fat loss. Hitting macros matters more than food quality. Stay consistent.`,
      `Maintain or increase strength in the gym. Don't do excessive cardio — 150-200 min/week is sufficient. Adherence > Perfection.`,
    ],
    endurance: [
      `Build aerobic base with steady-state cardio first. Add interval training gradually. Recovery is crucial for endurance adaptations.`,
      `Fuel adequately before and after training. Hydration strategy is critical for performance. Listen to your body.`,
      `Combine different intensities: easy days, tempo work, and hard intervals. Periodize training to avoid overtraining.`,
    ],
    flexibility: [
      `Consistency matters more than intensity. Stretch all major muscle groups daily. Improve mobility gradually over weeks/months.`,
      `Focus on breathing and body awareness. Don't push into pain. Breathe deeply during stretches for maximum benefit.`,
      `Combine flexibility work with light strength training to prevent injury. A flexible body is resilient.`,
    ],
    'general-fitness': [
      `Aim for consistency and sustainability. Exercise 3-5 days per week. Find movements that feel good and match your lifestyle.`,
      `Balance training, nutrition, sleep, and stress management. These pillars matter equally. Listen to your body.`,
      `If something hurts, rest. If a program feels unsustainable, modify it. Long-term consistency beats short-term perfection.`,
    ],
    performance: [
      `Periodize your training: build base strength, then add power and speed work. Deload every 4-6 weeks for recovery.`,
      `Sport-specific movements should match your goals. Work on weak links first. Video your lifts to check form.`,
      `Combine training with adequate sleep and nutrition. Performance athletes recover hard. Rest days are training days.`,
    ],
  },
  meals: enMeals,
};

const tr = {
  timing: {
    breakfast: 'Uyanıştan sonra 1 saat içinde',
    lunch: 'Öğle vakti (12-13:00)',
    dinner: 'Akşam (18-20:00)',
    snackWorkout: 'Antrenman öncesi veya sonrası',
    snackRest: 'Öğleden sonra veya akşam',
    asNeeded: 'Gerektiğinde',
  },
  fallbackMeal: {
    name: 'Esnek öğün (senin seçimin)',
    description:
      'Alerji filtrelerin bu öğün için tüm seçeneklerimizi eliyor. Gösterilen kalori ve makro hedeflerine yakın, tolere edebildiğin herhangi bir öğünü seçebilirsin.',
  },
  advice: {
    'build-muscle': [
      `Aşamalı yüklenmeye odaklan — haftalık 1-2 tekrar veya 2-5 kg ekle. Günde 7-9 saat uyu. Tutarlılık, yoğunluktan önemlidir. Antrenmanlarını takip et.`,
      `Bileşik hareketlere öncelik ver. Pompayı kovalama; güç ve hacme odaklan. Kaliteli form yaralanmaları önler ve kazanımları artırır.`,
      `Her öğünde protein tüket (kg başına 1.6-2.2g). Kalori fazlası şarttır, ama aşırı yeme — haftada 0.25-0.5 kg kilo artışını hedefle.`,
    ],
    'lose-weight': [
      `Orta düzeyde bir kalori açığı koru (-300-500 kal). Çok agresif açık kas kaybına ve metabolik uyuma yol açar. Haftada 0.25-0.5 kg kaybı hedefle.`,
      `Yağ kaybı sırasında kası korumak için proteine öncelik ver. Makrolara uymak, yiyecek kalitesinden daha önemlidir. Tutarlı kal.`,
      `Spor salonunda güç koru veya artır. Aşırı kardiyo yapma — haftada 150-200 dakika yeterlidir. Bağlılık > Mükemmellik.`,
    ],
    endurance: [
      `Önce sabit tempolu kardiyoyla aerobik taban oluştur. Aralıklı antrenmanı kademeli ekle. Toparlanma, dayanıklılık adaptasyonu için kritiktir.`,
      `Antrenman öncesi ve sonrasında yeterince beslen. Hidrasyon stratejisi performans için kritiktir. Bedenini dinle.`,
      `Farklı yoğunlukları birleştir: kolay günler, tempo çalışması ve sert aralıklar. Aşırı antrenmandan kaçınmak için periyodize et.`,
    ],
    flexibility: [
      `Tutarlılık, yoğunluktan daha önemlidir. Tüm büyük kas gruplarını her gün esnet. Haftalar/aylar içinde hareketliliği kademeli iyileştir.`,
      `Nefese ve beden farkındalığına odaklan. Acıya zorlama. Maksimum fayda için germe sırasında derin nefes al.`,
      `Yaralanmaları önlemek için esneklik çalışmasını hafif güç antrenmanıyla birleştir. Esnek bir vücut dayanıklıdır.`,
    ],
    'general-fitness': [
      `Tutarlılık ve sürdürülebilirliği hedefle. Haftada 3-5 gün egzersiz yap. Kendine iyi gelen ve yaşam tarzınla uyumlu hareketleri bul.`,
      `Antrenman, beslenme, uyku ve stres yönetimini dengele. Bu dört temel eşit derecede önemlidir. Bedenini dinle.`,
      `Bir şey acıtıyorsa dinlen. Program sürdürülemez hissettiriyorsa değiştir. Uzun vadeli tutarlılık, kısa vadeli mükemmelliği geçer.`,
    ],
    performance: [
      `Antrenmanını periyodize et: önce temel güç oluştur, sonra patlama ve hız çalışması ekle. Her 4-6 haftada bir dinlenme haftası uygula.`,
      `Spora özgü hareketler hedeflerinle örtüşmeli. Önce zayıf halkaları güçlendir. Formu kontrol etmek için kaldırışlarını kaydet.`,
      `Antrenmanı yeterli uyku ve beslenmeyle birleştir. Performans sporcuları sert toparlanır. Dinlenme günleri de antrenman günleridir.`,
    ],
  },
  meals: trMeals,
};

export function getPlanStrings(lang) {
  return lang === 'tr' ? tr : en;
}
